replicaCount: 1

image:
  repository: ghcr.io/ilmakiage/argocd-bitbucket-proxy
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  argocdWebhookURL: "http://argocd-applicationset-controller.argocd.svc.cluster.local:7000/api/webhook"
  logLevel: "info"

secrets:
  bitbucketServerSecret: ""
  bitbucketCloudSecret: ""

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
