apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd-bitbucket-proxy.fullname" . }}
  labels:
    {{- include "argocd-bitbucket-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "argocd-bitbucket-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "argocd-bitbucket-proxy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: ARGOCD_WEBHOOK_URL
              value: {{ .Values.env.argocdWebhookURL | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.logLevel | quote }}
            {{- if .Values.secrets.bitbucketServerSecret }}
            - name: BITBUCKET_SERVER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "argocd-bitbucket-proxy.fullname" . }}
                  key: bitbucket-server-secret
            {{- end }}
            {{- if .Values.secrets.bitbucketCloudSecret }}
            - name: BITBUCKET_CLOUD_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "argocd-bitbucket-proxy.fullname" . }}
                  key: bitbucket-cloud-secret
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
