{{- if or .Values.secrets.bitbucketServerSecret .Values.secrets.bitbucketCloudSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-bitbucket-proxy.fullname" . }}
  labels:
    {{- include "argocd-bitbucket-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.bitbucketServerSecret }}
  bitbucket-server-secret: {{ .Values.secrets.bitbucketServerSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.bitbucketCloudSecret }}
  bitbucket-cloud-secret: {{ .Values.secrets.bitbucketCloudSecret | b64enc | quote }}
  {{- end }}
{{- end }}
